### ISSUE TITLE
[request] swap scroll direction of touchpad

### ISSUE THREAD

**Issue by iamashwin99** [ris58h/exkeymo-web#10]
I was curious if in a similar fashion, the scroll direction of th touchpad could be swapped. 
I am used to the reverse scrolling (swipe up to move page down) but for some reason my bluetooth touchpad defaults to the natural scrolling ( swipe down to move page down) and I have sofar no found a way to change it.

**Comment by ris58h** [comment]
I don't think that it's related to keyboard mapping. You could check the docs though https://source.android.com/docs/core/interaction/input/key-character-map-files
