### ISSUE TITLE
[question] Can it work for power key?

### ISSUE THREAD

**Issue by Freed-Wu** [ris58h/exkeymo-web#12]
I try to swap power key and forward del key because I don't want to get <kbd>delete</kbd> by pressing <kbd>Fn</kbd> + <kbd>power</kbd>.

![IMG20240223164613](https://github.com/ris58h/exkeymo-web/assets/32936898/2d9aac27-eb5d-4a06-a5b8-e613192d3b81)

![Screenshot from 2024-02-23 16-46-56](https://github.com/ris58h/exkeymo-web/assets/32936898/db914794-96de-4874-ac98-93530fe8d759)

As a result, <kbd>delete</kbd> have been remapped to <kbd>power</kbd>, however, <kbd>power</kbd> still be <kbd>power</kbd>, which will wake up/sleep. Can this program work for power key?

**Comment by ris58h** [comment]
Sorry I just don't know.

**Comment by Freed-Wu** [comment]
I doubt the key code of the keyboard is AVR_POWER or STB_POWER not POWER. How to see the keycode of a keyboard?

And AVR, STB seem to be missing due to ˋhttps://github.com/ris58h/exkeymo-web/issues/5

**Comment by ris58h** [comment]
> How to see the keycode of a keyboard?

From the ExKeyMo docs:
> Some keyboards have media-keys or other keys that don't work as expected.
> To remap them you should find out what scan codes they produce.
> There are several Android apps to do it.
> For example [Gamepad tester](https://play.google.com/store/apps/details?id=ru.elron.gamepadtester)

**Comment by ris58h** [comment]
Seems like there 2 `POWER` keys in the dropdown (codes 116 and 152). Could you try another one?

**Comment by Freed-Wu** [comment]
You are right! 116 is correct. Not 152. Thanks!

**Comment by Freed-Wu** [comment]
And two power can be added to README.md and docs to let people notice it.
