### ISSUE TITLE
Compose Key

### ISSUE THREAD

**Issue by MicaelJarniac** [ris58h/exkeymo-web#2]
Is it possible to use the Compose Key on Android?

On my computer, I use it all the time to insert chars like "áçãà" and so on, and I do miss it on Android.

**Comment by ris58h** [comment]
Hi. I'm not sure about it. There is possibility to use RightAlt as additional layer, so you probably could put those chars on that layer.

**Comment by MicaelJarniac** [comment]
I've found an app that seems promising, and I've opened a feature request there to maybe add Compose key functionality:

https://github.com/keymapperorg/KeyMapper/issues/1093
